name: Build and Commit PDF Resume

on:
  push:
    paths:
    - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install TeXLive
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra

    - name: Compile LaTeX document
      working-directory: ./resume
      run: |
        pdflatex main.tex
        mv main.pdf frank_robert_resume_$(date +'%Y').pdf

    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        add: 'resume'
        author_name: Frank Robert
        author_email: frankie.robert@gmail.com
